### PR TITLE
Fixed init/exit logic being flipped in ActionGeneric

### LINKED ISSUE #35: Wrong method invocation in base class ActionGeneric.cs
In script [ActionGeneric.cs](https://github.com/ashblue/fluid-behavior-tree/blob/develop/Assets/FluidBehaviorTree/Runtime/Tasks/Actions/ActionGeneric.cs) method `OnExit` call `initLogic` and `OnInit` call `exitLogic`.

```charp
protected override void OnExit () {
    initLogic?.Invoke();
}

protected override void OnInit () {
    exitLogic?.Invoke();
}
```

### PR DESCRIPTION
**Pull request by piotr-j**
Also updated test to demonstrate the problem. 
Fixes #35

### CODE REVIEW

**Comment by ashblue** [comment]
The commit message probably won't lint according to the commit linter standards. I'll get this refactored so it passes the CI checks.

**Comment by piotr-j** [comment]
Oops my bad! Must have missed some info. Sorry about that.

**Comment by ashblue** [comment]
@piotr-j no worries, yeah you have to make commits with commitizen. It gets auto converted to docs and releases. CI linter prevents anything going through that doesn't match the syntax. https://github.com/ashblue/fluid-behavior-tree#making-commits

**Comment by ashblue** [comment]
Closing in favor of #41

**Pull request closed without merging**
