### PR TITLE
fix(conditions): generic condition had exit and init reversed

### PR DESCRIPTION
**Pull request by hookSSi**
Didn't seem to cause any problems. But would have definitely caused issues with extending the
ConditionGeneric class.

### CODE REVIEW

**Comment by hookSSi** [comment]
I wrote a PR according to the guidelines.

This is my first experience, so I don't know if I did well.

By all means, I would like you to share your opinion with a beginner like me.

**Comment by ashblue** [comment]
@hookSSi this looks solid. I'll pull down the code and verify everything this weekend (would sooner but my job has been a bit crazy this week with a huge upcoming release).

I think the test needs to be adjusted slightly to prevent a potential regression. But I can do that real quick 👍

**Comment by ashblue** [comment]
@all-contributors please add @hookSSi for 💻

**Comment by ashblue** [comment]
@all-contributors please add @hookSSi for code

**Comment by hookSSi** [comment]
I'm so sorry for that.

Thank you for your kind and detailed explanation even in the midst of a busy time.

Finally, what I hit wrong was made "Merge branch'develop' into feature/condition-generic-exit-init-bug".

Hope this doesn't make you uncomfortable.

**Comment by ashblue** [comment]
@hookSSi I double checked everything and it all looks great 👍  Feel free to merge.

**Review by ashblue — APPROVED** [review]

**Pull request merged**
