### PR TITLE
fix(nodeprintcontroller.cs): #29 Line offset bug

### LINKED ISSUE #29: Minor editor rendering glitch
Thanks for this very nice behavior tree implementation! 

I found a minor cosmetic issue, which doesn't seem to affect the functionality or usability:

When rendering behavior trees in the editor, the horizontal lines are a bit off:
grafik

fluid-behavior-tree version: 2.2.2 (included using the Unity package manager)
Unity: 2019.4.10f1 Personal
OS: macOS 10.15.6

### PR DESCRIPTION
**Pull request by TNThomas**
Horizontal lines moved up 2 pixels. Vertical lines underneath boxes extended by 1 pixel.

fix #29

### CODE REVIEW

**Comment by ashblue** [comment]
I've got a few edge case projects to test this against. Should have time this weekend 👍

**Comment by ashblue** [comment]
This kinda fixes it, but looks like it introduces a gap that shouldn't be there. Should be a continuous line. Hopefully easy to fix

image

**Comment by TNThomas** [comment]
Found and fixed one instance of broken lines, but it didn't look like the ones in your screenshot (not sure how you produced those).

**Comment by ashblue** [comment]
I'll take a look today. See if the issue went away

**Comment by ashblue** [comment]
Definitely seeing the issue still in the built in example trees. Can you post a screenshot of how it looks on your end? Also what OS are you using?

**Comment by TNThomas** [comment]
I am using Windows 11. I'll get a screenshot for you after GGJ is over

**Comment by TNThomas** [comment]
image

**Comment by ashblue** [comment]
Weird... I'll have to dig into this a bit more. Sorry for the delay getting this in.

**Comment by ashblue** [comment]
Might have an idea what's causing this, should get addressed in the next bundle of patches.

**Comment by ashblue** [comment]
Closing in favor of #97

**Pull request closed without merging**
